-- Basic
require('core.plugins')
require('core.configs')
require('core.colors')

-- Mappings
require('mappings.base')
require('mappings.neotree')
-- require('mappings.oil')
-- require('mappings.nvim-tree')
require('mappings.lsp')
require('mappings.telescope')
require('mappings.toggleterm')
require('mappings.neogen')
require('mappings.luasnip')
require('mappings.nvim-dap')
require("mappings.osc52")
require("mappings.neotest")

-- Plugins
require('plugins.lsp')
require('plugins.neotree')
require('plugins.todo-comments')
require('plugins.lsp_signature')
-- require('plugins.nvim-tree')
require('plugins.nvim-lsp-file')
require('plugins.treesitter')
require('plugins.cmp')
require('plugins.mason')
require('plugins.none-ls')
require('plugins.lualine')
require('plugins.toggleterm')
require('plugins.luasnip')
require("plugins.nvim-dap")
require("plugins.neotest")
require('plugins.leap')
require('plugins.remote-ssh')
require('plugins.venv-selector')
require('plugins.aerial')
-- require("plugins.multicursor")
require("plugins.telescope")
require("plugins.skel")
require('plugins.neozoom')
-- require('plugins.nvim-ufo')
